apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-storage-config
  namespace: istio-system
data:
  thanos-storage-config.yaml: |
    type: s3
    config:
      bucket: thanos-metrics-pst #S3 bucket name
      endpoint: s3.us-east-1.amazonaws.com #S3 Regional endpoint
      access_key: "key"
      secret_key: "secret"
      region: "us-east-1"
